### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by kishaningithub** [podefr/react-debounce-render#14]
I use typescript for react projects. If this project can be added to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) we can

```
npm install @types/react-debounce-render
```

and use this awesome package in typescript projects.

**Comment by podefr** [comment]
Hi Kishan, this is a great idea. Would you be able to create a PR on the DefinitelyTyped repository? I'm happy to provide you with the support you need

Thanks!
Olivier

**Comment by ibarapascal** [comment]
@podefr I've written the typescript version of it. Since this package is small enough, shall I directly publish a typescript lib of it ? (rather than @types) I'm a totally new hand about those stuff and it's worth a try for me I guess.  
Update: done: [react-debounce-rendering](https://www.npmjs.com/package/react-debounce-rendering)

**Comment by podefr** [comment]
Hi, sorry for the late reply. Thanks for rolling out a typescript version. I think I'd rather avoid the complexity of maintaining/deploying a pure typescript version of this lib and would rather have a definitelyTyped library if that works for you.

**Comment by podefr** [comment]
typescript was added as of Jan 29 2022 with version 8.0.1
